name: Deploy react-app 

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy Static Website Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./"
          target: "/tmp/static-site"
          strip_components: 1

      - name: Deploy to NGINX Web Directory via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if ! command -v nginx > /dev/null; then            # Check and install nginx if not present
              echo "Nginx not found. Installing Nginx..."
              sudo apt update
              sudo apt install -y nginx
              sudo systemctl enable nginx
              sudo systemctl start nginx
            else
              echo "Nginx is already installed."
            fi

                  # Deploy static site
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/static-site/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo systemctl reload nginx

      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E397NGYCC4RRV8 \
            --paths "/*"  

        
